export const FSQUARE_CLIENT_ID = "RIBNFBTHR5ND4FGFQPGF4W4Z2P5OYFEGBM1R1RWNLYVTTEC0";
export const FSQUARE_CLIENT_SECRET = "IREGOQDZSVPS3N52V31KYVCVVXS3DHSIEAQFMJLN0IR10AAA";
export const GOOGLE_MAPS_KEY = "AIzaSyDNMte3ZwfssRDYPzNb7bWYuNbhLpXAccY";
